#!/bin/bash

CGO_LDFLAGS_ALLOW='-Wl,--unresolved-symbols=ignore-in-object-files' \
    go build -ldflags="-s -w" -v docker-sriov-plugin || exit 1

exec docker build --progress plain --force-rm -t rdma/sriov-plugin:dev -f Dockerfile-dev .
